export const RECURSIVE_RMDIR_NODE_VERSION_SUPPORT = '12.10';
export const RM_NODE_VERSION_SUPPORT = '14.14';

export const RECURSIVE_RMDIR_IGNORED_ERROR_CODES: string[] = [
  'ENOTEMPTY',
  'EEXIST',
];
