/* eslint-disable quotes */
import colors from 'colors';

interface HelpSection {
  id: string;
  title: string;
  icon: string;
  content: string[];
}

export const HELP_SECTIONS: HelpSection[] = [
  {
    id: 'welcome',
    title: 'Welcome',
    icon: '👋',
    content: [
      colors.bold('Welcome to npkill!'),
      '',
      'Npkill helps you find and manage "junk" directories',
      'left behind by development tools.',
      '',
      'These folders are essential while working on projects,',
      'but over time they pile up, eating tons of space long',
      "after you've moved on.",
      '',
      'Npkill scans your directories, lists these folders with',
      'their sizes, and shows when you last touched each project,',
      'so you can quickly decide what to keep and what to clean.',
      '',
      colors.green.bold('Easy and powerful!'),
    ],
  },
  {
    id: 'navigation',
    title: 'Navigation',
    icon: '🗺️',
    content: [
      colors.bold.bgYellow.black(' Basic Movement '),
      '',
      `${colors.green('↑ / k')}              Move up`,
      `${colors.green('↓ / j')}              Move down`,
      `${colors.green('→ / l')}              Next panel`,
      `${colors.green('← / h')}              Previous panel`,
      '',
      colors.bold.bgYellow.black(' Fast Movement '),
      '',
      `${colors.green('PgUp / Ctrl+u / u')}  Page up`,
      `${colors.green('PgDown / Ctrl+d / d')} Page down`,
      `${colors.green('Home')}               First item`,
      `${colors.green('End')}                Last item`,
      '',
      colors.bold.bgYellow.black(' Other '),
      '',
      `${colors.green('q / ESC')}            Quit npkill`,
      `${colors.green('e')}                  Show errors`,
    ],
  },
  {
    id: 'deletion',
    title: 'Deletion',
    icon: '🗑️',
    content: [
      colors.bold('Managing your folders'),
      '',
      `${colors.green('SPACE / DEL')}       Delete selected folder`,
      `${colors.green('t')}                 Toggle selection mode`,
      `${colors.green('v')}                 Start range selection`,
      `${colors.green('a')}                 Select/deselect all`,
      `${colors.green('ENTER')}             Delete selected (multi-mode only)`,
      '',
      colors.bold.yellow('⚠️  Selection Mode'),
      '',
      'Press "t" to enter multi-selection mode. In this mode,',
      'you can mark multiple folders before deleting them all',
      'at once with ENTER.',
      '',
      'Press "v" to start a range selection from current item.',
      'Move to another item and press "v" again to select the',
      'entire range.',
      '',
      'Press "a" to quickly select or deselect all folders.',
    ],
  },
  {
    id: 'panels',
    title: 'Panels',
    icon: '📋',
    content: [
      colors.bold('Understanding the interface'),
      '',
      colors.bold.cyan('Results Panel (Main)'),
      'Lists all found directories with their sizes.',
      'Navigate with arrow keys or j/k.',
      'Press SPACE to delete a folder.',
      'Press → to see details.',
      '',
      colors.bold.cyan('Info Panel'),
      'Shows detailed information about the selected folder:',
      '  • Full path',
      '  • Size',
      '  • Last modification date',
      '  • Number of files',
      '  • Warnings (if applicable)',
      '',
      colors.bold.cyan('Options Panel'),
      'Configure npkill settings on the fly:',
      '  • Change target folders',
      '  • Modify search directory',
      '  • Set exclusions',
      '  • Change sort order',
      '  • Adjust cursor color',
      '  • Toggle dry-run mode',
      '',
      colors.bold.cyan('Help Panel (You are here!)'),
      'Navigate through help sections.',
      'Use ↑/↓ to change sections.',
      'Scroll content with j/k or arrow keys.',
    ],
  },
  {
    id: 'header',
    title: 'Header Info',
    icon: '📊',
    content: [
      colors.bold('Understanding the header'),
      '',
      colors.bold.green('Potential Space'),
      'The total size of all detected directories.',
      'This represents the maximum possible space you could',
      "free if you deleted everything (which you shouldn't!).",
      '',
      colors.bold.green('Freed Space'),
      'The space actually recovered in this session.',
      '',
      colors.bold.yellow('Progress Bar'),
      '',
      'The progress bar has 3 color-coded parts:',
      '',
      ` ${colors.green('▀▀▀▀▀▀▀')} Green  → Results ready (stats calculated)`,
      ` ${colors.white('▀▀▀▀▀▀▀')} White  → Directories examined`,
      ` ${colors.gray('▀▀▀▀▀▀▀')} Gray   → Pending to be analyzed`,
      '',
      'Full bar example:',
      ` ${colors.green('▀▀▀▀▀▀▀')}${colors.white('▀▀▀▀')}${colors.gray('▀▀▀▀▀▀▀▀▀▀▀')}`,
      '',
      colors.bold.cyan('Additional Context'),
      '',
      'The header also displays:',
      '  • Selection mode status',
      '  • Dry-run mode indicator',
      '  • Current sort order',
      '  • Active filters',
    ],
  },
  {
    id: 'warnings',
    title: 'Warnings',
    icon: '⚠️',
    content: [
      colors.bold.yellow('Important: Not all results are safe to delete!'),
      '',
      'Some applications (VSCode, Discord, Slack, etc.) need',
      'their dependencies to work. If their directory is deleted,',
      'the application will probably break until dependencies',
      'are reinstalled.',
      '',
      colors.bold('What does ⚠️  mean?'),
      '',
      'When you see this warning symbol next to a result,',
      'it means npkill has detected that this folder might',
      "belong to an application that's currently installed",
      'on your system.',
      '',
      colors.bold.red('Be careful!'),
      '',
      'Always think twice before deleting folders with the',
      'warning symbol. Consider:',
      '',
      '  • Is this application still in use?',
      '  • Do I need this app to work right now?',
      '  • Can I easily reinstall it if needed?',
      '',
      colors.bold.green('Pro tip:'),
      'Use the Info panel (→) to see more information',
      'about why a folder is flagged.',
    ],
  },
  {
    id: 'shortcuts',
    title: 'Quick Reference',
    icon: '⌨️',
    content: [
      colors.bold.bgCyan.black(' Essential Shortcuts '),
      '',
      colors.yellow('Navigation'),
      `  ${colors.green('↑/↓ or j/k')}       Move cursor`,
      `  ${colors.green('←/→ or h/l')}       Switch panels`,
      `  ${colors.green('PgUp/PgDown')}      Fast scroll`,
      '',
      colors.yellow('Actions'),
      `  ${colors.green('SPACE or DEL')}     Delete folder`,
      `  ${colors.green('t')}                Multi-select mode`,
      `  ${colors.green('v')}                Range selection`,
      `  ${colors.green('ENTER')}            Confirm multi-delete`,
      `  ${colors.green('o')}                Open parent folder`,
      '',
      colors.yellow('Panels'),
      `  ${colors.green('→ or l')}           Details/Next`,
      `  ${colors.green('← or h')}           Options/Previous`,
      `  ${colors.green('e')}                Show errors`,
      '',
      colors.yellow('Exit'),
      `  ${colors.green('q or ESC')}         Quit npkill`,
    ],
  },
  {
    id: 'tips',
    title: 'Tips & Tricks',
    icon: '💡',
    content: [
      colors.bold('Get the most out of npkill'),
      '',
      colors.bold.cyan('1. Use profiles'),
      '   Start with profiles for common tools:',
      '   npkill -p node,python,java.',
      '',
      colors.bold.cyan('2. Sort intelligently'),
      '   Sort by size to find the biggest space hogs:',
      '   npkill --sort size',
      '   Or by last-mod to find abandoned projects.',
      '',
      colors.bold.cyan('3. Exclude what you need'),
      '   Protect important directories:',
      '   npkill -E ".git,important_project"',
      '',
      colors.bold.cyan('4. Try dry-run mode'),
      '   Test without risk using --dry-run.',
      '   Nothing is deleted!',
      '',
      colors.bold.cyan('5. Multi-select workflow'),
      '   Press "t" to enter selection mode.',
      '   Mark folders with SPACE.',
      '   Press ENTER to delete all at once.',
      '',
      '   Press "v" on first item.',
      '   Move to last item and press "v" again.',
      '   All items in between are selected!',
      '',
      colors.bold.cyan('6. Check details first'),
      '   Unsure about a result? Press → to see',
      '   more details.',
    ],
  },
  {
    id: 'about',
    title: 'About',
    icon: 'ℹ️',
    content: [
      colors.bold('About npkill'),
      '',
      'npkill is an open-source tool designed to help',
      'developers reclaim disk space by finding and removing',
      'unnecessary dependency folders.',
      '',
      colors.bold.cyan('Get Involved'),
      '',
      'GitHub: github.com/voidcosmos/npkill',
      'Report bugs, request features, contribute!',
      '',
      colors.bold.cyan('License'),
      '',
      'MIT License - Free and open source',
      '',
      '',
      colors.dim('Made with ❤️'),
    ],
  },
];
