/* eslint-disable quotes */
import colors from 'colors';

interface HelpSection {
  id: string;
  title: string;
  icon: string;
  content: string[];
}

export const HELP_SECTIONS: HelpSection[] = [
  {
    id: 'welcome',
    title: 'Welcome',
    icon: '👋',
    content: [
      colors.bold('Welcome to npkill!'),
      '',
      'Npkill helps you find and manage "junk" directories',
      'left behind by development tools.',
      '',
      'These folders are essential while working on projects,',
      'but over time they pile up, eating tons of space long',
      "after you've moved on.",
      '',
      'Npkill scans your directories, lists these folders with',
      'their sizes, and shows when you last touched each project,',
      'so you can quickly decide what to keep and what to clean.',
      '',
      colors.green.bold('Easy and powerful!'),
    ],
  },
  {
    id: 'shortcuts',
    title: 'Quick Reference',
    icon: '⌨️',
    content: [
      colors.cyan(colors.bold('Navigation')),
      `  ${colors.green('↑/↓ or j/k')}       Move cursor.`,
      `  ${colors.green('←/→ or h/l')}       Switch panels.`,
      `  ${colors.green('PgUp/PgDown')}      Fast scroll.`,
      `  ${colors.green('Home/End')}         Jump to first/last.`,
      '',
      colors.cyan(colors.bold('Actions (normal mode)')),
      `  ${colors.green('SPACE / DEL')}      Delete folder.`,
      `  ${colors.green('o')}                Open parent folder.`,
      `  ${colors.green('t')}                Enter ${colors.green('multi-select mode')}.`,
      '',
      colors.cyan(colors.bold('Actions (multi-select mode)')),
      `  ${colors.green('t')}                Back to ${colors.green('normal mode')} without delete.`,
      `  ${colors.green('v')}                Range selection.`,
      `  ${colors.green('a')}                Select/deselect all.`,
      `  ${colors.green('SPACE')}            Select/deselect current.`,
      `  ${colors.green('ENTER')}            Delete selected folders.`,
      '',
      colors.cyan(colors.bold('Others')),
      `  ${colors.green('e')}                Show errors.`,
      `  ${colors.green('q / ESC')}          Quit npkill.`,
    ],
  },
  {
    id: 'header',
    title: 'Header Info',
    icon: '📊',
    content: [
      colors.bold('Understanding the header'),
      '',
      colors.bold.green('Potential Space'),
      'The total size of all detected directories.',
      'This represents the maximum possible space you could',
      'free if you deleted everything.',
      '',
      colors.bold.green('Freed Space'),
      'The space actually recovered in this session.',
      '',
      colors.bold.green('Last Modified (last-mod)'),
      'Shows when the last file in the parent workspace was',
      'modified. This helps identify abandoned projects.',
      '',
      colors.dim('Note: This checks the entire parent directory,'),
      colors.dim('not just the target folder itself.'),
      '',
      colors.bold.green('Progress Bar'),
      'The progress bar has 3 color-coded parts:',
      '',
      ` ${colors.green('▀▀▀▀')} Green  → Results ready (stats calculated)`,
      ` ${colors.white('▀▀▀▀')} White  → Directories examined`,
      ` ${colors.gray('▀▀▀▀')} Gray   → Pending to be analyzed`,
      '',
      'Full bar example:',
      ` ${colors.green('▀▀▀▀▀▀▀')}${colors.white('▀▀▀▀')}${colors.gray('▀▀▀▀▀▀▀▀▀▀▀')}`,
    ],
  },
  {
    id: 'warnings',
    title: 'Warnings',
    icon: '⚠️',
    content: [
      colors.bold.yellow('Important: Not all results are safe to delete!'),
      '',
      'Some applications (VSCode, Discord, Slack, etc.) need',
      'their dependencies to work. If their directory is deleted,',
      'the application will probably break until dependencies',
      'are reinstalled.',
      '',
      'Npkill will try to detect this folders and show "⚠️"',
      'alongside the result and mark it as "sensitive".',
      '',
      '',
      colors.bold.green('Pro tip'),
      'Use the Info panel (→) to see more information',
      'about why a folder is flagged.',
    ],
  },
  {
    id: 'panels',
    title: 'Panels',
    icon: '📋',
    content: [
      colors.bold('Understanding the interface'),
      '',
      colors.bold.cyan('Delete Panel (Main)'),
      'Lists all found directories with their sizes.',
      'Navigate with arrow keys or j/k.',
      'Press SPACE to delete a folder.',
      'Press → to see details.',
      '',
      colors.bold.cyan('Info Panel'),
      'Shows details of the selected result. Plus notes',
      'that might be useful to you.',
      '',
      colors.bold.cyan('Options Panel'),
      'Configure npkill settings on the fly.',
      '',
      colors.bold.cyan('Help Panel (You are here!)'),
      'Navigate through help sections.',
      'Use ↑/↓ to change sections.',
      'Scroll content with j/k or arrow keys.',
    ],
  },
  //   { // TODO pending to add .npkillrc support
  //     id: 'config',
  //     title: 'Configuration',
  //     icon: '⚙️',
  //     content: [
  //       colors.bold('Customizing npkill with .npkillrc'),
  //       '',
  //       colors.bold.cyan('What is .npkillrc?'),
  //       'A configuration file where you can set your default',
  //       'preferences, custom profiles, and target folders.',
  //       '',
  //       colors.bold.cyan('Location'),
  //       '',
  //       'Place it in your home directory:',
  //       colors.dim('  ~/.npkillrc'),
  //       '',
  //       'Or load from a custom location:',
  //       colors.green('  npkill --config /path/to/config'),
  //       '',
  //       colors.bold.cyan('Example Configuration'),
  //       '',
  //       colors.dim('{'),
  //       colors.dim('  "targets": ["node_modules", ".venv", "target"],'),
  //       colors.dim('  "exclude": [".git", "important-project"],'),
  //       colors.dim('  "sortBy": "size",'),
  //       colors.dim('  "backgroundColor": "bgCyan",'),
  //       colors.dim('  "excludeHiddenDirectories": true,'),
  //       colors.dim('  "profiles": {'),
  //       colors.dim('    "mystack": {'),
  //       colors.dim('      "targets": ["node_modules", "venv", "target"]'),
  //       colors.dim('    }'),
  //       colors.dim('  }'),
  //       colors.dim('}'),
  //       '',
  //       colors.bold.cyan('Available Options'),
  //       `${colors.green('targets')}              Target folder names to search`,
  //       `${colors.green('exclude')}              Directories to skip`,
  //       `${colors.green('sortBy')}               Default sort (size/path/last-mod)`,
  //       `${colors.green('backgroundColor')}      Cursor highlight color`,
  //       `${colors.green('sizeUnit')}             Display unit (auto/mb/gb)`,
  //       `${colors.green('profiles')}             Custom profile definitions`,
  //     ],
  //   },
  {
    id: 'profiles',
    title: 'Profiles',
    icon: '📦',
    content: [
      colors.bold('Working with profiles'),
      '',
      colors.bold.cyan('What are profiles?'),
      'Profiles are presets of target folders for different',
      'programming languages and tools.',
      '',
      colors.bold.cyan('Usage'),
      'List available profiles:',
      colors.green('  npkill -p'),
      '',
      'Single profile:',
      colors.green('  npkill -p node'),
      '',
      'Multiple profiles:',
      colors.green('  npkill -p node,python,java'),
      '',
      // colors.bold.cyan('Custom Profiles'),
      //   'Define your own in .npkillrc:',
      //   '',
      //   colors.dim('"profiles": {'),
      //   colors.dim('  "webdev": {'),
      //   colors.dim('    "targets": ["node_modules", "dist", ".next"]'),
      //   colors.dim('  }'),
      //   colors.dim('}'),
      //   '',
      //   'Then use:',
      // colors.green('  npkill -p webdev'),
    ],
  },
  {
    id: 'tips',
    title: 'Tips & Tricks',
    icon: '💡',
    content: [
      colors.bold('Get the most out of npkill'),
      '',
      colors.bold.cyan('1. Use profiles'),
      '   Start with profiles for common tools:',
      `   ${colors.green('npkill -p node,python,java')}.`,
      '',
      colors.bold.cyan('2. Sort intelligently'),
      '   Sort by size to find the biggest space hogs:',
      `   ${colors.green('npkill --sort size')}`,
      '   Or by last-mod to find abandoned projects.',
      '',
      colors.bold.cyan('3. Exclude what you need'),
      '   Protect important directories:',
      `   ${colors.green('npkill -E ".git,important_project"')}`,
      '',
      colors.bold.cyan('4. Try dry-run mode'),
      '   Test without risk using --dry-run.',
      '   Nothing is deleted! (simulated with delay).',
      '',
      colors.bold.cyan('5. Multi-select workflow'),
      '   Press "t" to enter selection mode.',
      '   Mark folders with SPACE.',
      '   Press ENTER to delete all at once.',
      '',
      '   Press "v" on first item.',
      '   Move to last item and press "v" again.',
      '   All items in between are selected!',
      '',
      colors.bold.cyan('6. Check details first'),
      '   Unsure about a result? Press → to see',
      '   more details.',
    ],
  },
  {
    id: 'about',
    title: 'About',
    icon: 'ℹ️',
    content: [
      colors.bold('About npkill'),
      '',
      'Npkill, a tool designed to help developers',
      'reclaim disk space by finding and removing',
      'unnecessary dependency folders.',
      '',
      colors.bold.cyan('Get Involved'),
      'GitHub: github.com/voidcosmos/npkill',
      'Report bugs, request features, contribute!',
      '',
      colors.bold.cyan('License'),
      'MIT License - Free and open source.',
      '',
      '',
      colors.dim('Made with ❤️'),
    ],
  },
];
